### ISSUE TITLE
Before not firing, next not a function, only one banner loading

### ISSUE THREAD

**Issue by 0dp** [brandlabs/bigcommerce-sitewide-banners#15]
First and foremost, thanks for putting the time and effort into this module.

I reckon some things have changed in cornerstone since last update.

I have the following issues that I hope we can find a solution for.

When following the documentation,
> On global.js file you need to call the getBanner() function based on your preferences (We like on the before function call)

It looks like before is not available anymore, or am I missing something?
Moving the initialization to onReady will load the banner as expected.
Though, there is a few issues with this.
1. Banners are first loaded on $(document).ready()
1. next() is not a function
1. It seems like only one banner gets loaded, (becuase the cb is not working?)

**Comment by hectorfhurtado** [comment]
@0dp thank you. Updated our README with instructions for using the package and BigCommerce new methods.

Also, I checked the package is still working creating a new store, running grunt task which creates the Category on the store (didn't have store credentials right at first :) ).

![image](https://user-images.githubusercontent.com/2037113/75715166-f8f8df00-5c9a-11ea-8be4-e87763e317ee.png)

![image](https://user-images.githubusercontent.com/2037113/75714355-8f2c0580-5c99-11ea-8119-b1eab92773f3.png)

![image](https://user-images.githubusercontent.com/2037113/75714414-a834b680-5c99-11ea-943e-ff19e04a354b.png)

Then, I created these three Banners (two for page top and one for bottom)

![image](https://user-images.githubusercontent.com/2037113/75714507-d87c5500-5c99-11ea-9fca-85b2e5354491.png)

All of them bound to the Sitewide banner category

![image](https://user-images.githubusercontent.com/2037113/75714604-06fa3000-5c9a-11ea-9e8f-040b19de0956.png)

Now, following the README instructions :) I placed all three banners on different parts of the page (one on top of page, another on top of page heading and the other one at the bottom) with this code on `global.js`

![image](https://user-images.githubusercontent.com/2037113/75714777-4fb1e900-5c9a-11ea-91d0-484bb419407c.png)

I placed it at the bottom of `onReady` function since I don't know if other function could interfere with my code but, I could place it anywhere if I'm sure nothing is going to mess with my reference DOM Elements.

Here is what I got on page top

![image](https://user-images.githubusercontent.com/2037113/75714952-9acbfc00-5c9a-11ea-87fe-8ce7215e5832.png)

and page bottom

![image](https://user-images.githubusercontent.com/2037113/75714986-a8818180-5c9a-11ea-8078-e64db4aaa61d.png)

Hope this helps

**Comment by 0dp** [comment]
Yeah it's great thank you.
After I wrote here, I forked the repo and messed about with it as well.

I do have one question though.
Does your banners also first load after page load?
For instance if you look at the top banner. It will load after the page is loading thus pushing the header down?
The fix for me was simple. Just adding a fixed height to the banner. But, I am curious if it's just me

**Comment by hectorfhurtado** [comment]
@0dp you're right, banners are loaded after page since they're inserted using JavaScript which is async loaded (banners content is AJAX'ed too while "critical" content is rendered first). So, it's a good idea reserving banner space if height is known (although, care should be taken for narrow devices: content sometimes is long enough to wrap into more lines) so page content doesn't jump down.

Hope this helps

**Comment by 0dp** [comment]
Indeed.

Again thanks for this great module. That leaves you wondering why the BC team have not thought of this use case many moons ago
